version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb/data:/data/db
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: Hong1234
      MONGODB_BIND_IP_ALL: "true"



